
import * as React from 'react';
import { Form, Text } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button } from 'react-native-paper';

import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: "testservice@mdlapptest.iam.gserviceaccount.com",
  key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFcxa6K1JWzs7F\nuJH85PFwyNPVCQdHrG/GLSTh1zAXqq6x63N4oIvXTVXxBmRXdG9b+PfTmMxEobt+\nK2VYbVsddYV4NCH8DIWax1yCXH11IqwODHrsdyty5rNKsekFE/3CiXUYgAw3RTZC\nsbSpy65vZUJ3CLjLwLiW7ntdGrrQCKRCky3Lz4i7qazF/Y6ngjjjwkoTYdbqBYsr\nPcPg+aFX2ChUhE+dFriRFSf8LGuSmNZQloJ82OLWH8satcfKNsCMGGVQU3sF6rhF\n4FPK23AzXDcuuhSqCC1437N1qnmTuermZhUBiN5tyFWRyYcE+ILpRXue4y6jz1tN\nJn6v4li9AgMBAAECggEABzCmMrhSIsQcJnoOouFpY1yEzjyqbbM7TMGnFqxB3ZLD\nEsqKpWlfPkNcLk83xzF/vp8l0yg8xAEJtVH6OkqdJ0j4x8RKOoXwNY8t8LdSgDn3\nfvl4XnUGeYQqIj2xSRSNyJA92dsL1tVn4OzcsdQvcXIEBhakuBK4BhMAHgdTpzCg\n3zvmZuWcqcDxOIn1haZkiCNte/G/IIZqKtzpoRKPKkE20G1Ov7znOIIufkaDbk5R\nM2zToT3V5Eq7uluOOJA629oKBSueNBB/1Yl4oHIBgED72SeFKR2qizJKcoP/dGyW\nOcGIhZvsrVicGags5KpUtY9Hp16LW+0ND0XP6hOEsQKBgQD+MPozeWeJ1NPSwSeu\nRxcUqDyMCXiY8xB94rrUvdy/2xMujCOtrCFAZJFdWsWjWyCCQES0NAnhZ0EoQHuO\nP++y8+dQr//Lhxj0zAJgNDgbZjijbmWED4KJuMM31O6I37pu4c7AVV7MqptV6evw\n8AASFBIuPZ84V8MpE3RkO3/NuQKBgQDG2sDeIbRCHu0hyNopJc34rXKU3FmnRlUl\nLLhNRKsKsvQqyj3bs4fKTHApMZJdgJoCrGUAUY4KDf3LxCctB8nuUQdrfhfJ6vrA\najn4vxCJthPZ5B53ipxq28BE1Wjc3dQvVjIlMLPGAC6BlbUWIDW0lemH/K20tGCe\niI2OzQ0FJQKBgERpHg1YcTsxIkkoXuuSim2u0YzGx8QyNpAKw0maR50C8uimIrwN\nBW31IwJC+cn7LoafkV4GW1pkla6lnBsure41ol2e4HMASwEnHsSRiUAmhLvHbF7c\nZb93EGMoVYJU5DIPZ7tvvnHKwL+gkzVnAj3bVQFI6F8bj5SwfbS0JrNRAoGBALaD\nGtgGSUMSzYTfq1Ru7VAcKfl1ERhVllqLZBEPQImOXEpV21alvbEwXRWB+Ru2qCRi\nBEW5lMunsdRvEaHj7zO7zTqcvcrG0CUAmnqzKsOqiSfIlyoS36O4VA0ZbqihNVnJ\nHDdELwxBKG4pcM6A+6nmmjQE943OrIt1O6/ghd29AoGBANIIBTAaHoD/5Dk20i4i\n7PGultjo1FoF+H40zTTBEAYGywBx6JCBiERV+nLMB/6U4cuzeSOTjHNua8LvhDUl\nOEPtLs3P33uNnlsZcvMPid+C5iFlg1vDmHMLNJzOp5OjmtmHyKBdpWzPoORMO21w\neyLL+GHpDIBlgj2UR60lW8IA\n-----END PRIVATE KEY-----\n",
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

const doc = new GoogleSpreadsheet('1tJ8tZx0B9V9tzbIuFpom1u6545r-uvE6We7E8tCUtQI', serviceAccountAuth);

await doc.loadInfo(); // loads document properties and worksheets
console.log(doc.title);
await doc.updateProperties({ title: 'renamed doc' });

const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
console.log(sheet.title);
console.log(sheet.rowCount);

// adding / removing sheets
const newSheet = await doc.addSheet({ title: 'another sheet' });
await newSheet.delete();

export default function OptionScreen() {
    return (
      <SafeAreaView>
        <Text>Option Screen</Text>
      </SafeAreaView>
    )
}